FROM  alpine:3.12.0

RUN apk update
RUN apk add openrc
RUN apk add php7-common php7-iconv php7-json php7-gd php7-curl php7-xml \
	php7-mysqli php7-imap php7-cgi fcgi php7-pdo php7-pdo_mysql php7-soap php7-xmlrpc \
	php7-posix php7-mcrypt php7-gettext php7-ldap php7-ctype php7-dom php7 php7-fpm php7-opcache

# RUN adduser --uid 82 www-data
# RUN addgroup -S nginx && adduser -S nginx -h /bin/bash -h /var/www/ -h /tmp -G nginx


# RUN mkdir -p /var/www/html
# WORKDIR /var/www/html/
# RUN cd /tmp
RUN wget https://wordpress.org/latest.tar.gz
RUN tar xvf latest.tar.gz
RUN rm latest.tar.gz
# RUN mv /tmp/wp-config.php /var/www/html/wordpress/wp-config.php
COPY src/wp-config.php /wordpress/wp-config.php
RUN openrc
RUN touch /run/openrc/softlevel
COPY src/run.sh /

# COPY src ./tmp/
COPY src/www.conf /etc/php7/php-fpm.d
# RUN sh tmp/wp-setup.sh
RUN chmod +x ./run.sh

# EXPOSE 9000

ENTRYPOINT [ "./run.sh" ]
# CMD ["php-fpm7", "-F"]
