FROM debian:buster

RUN apt-get update -y
RUN apt-get upgrade -y
RUN apt-get install openrc -y
RUN apt-get install php7.0 php7.0-fpm php7.0-gd php7.0-mysql

COPY src ./tmp/
RUN mkdir -p /var/www/localhost/htdocs

RUN sh tmp/wp-setup.sh
ADD src/run.sh .
RUN chmod +x /run.sh

EXPOSE 9000
ENTRYPOINT [ "/run.sh" ]
