FROM alpine:3.12.0

# EXPOSE 21
# EXPOSE 20
RUN apk add --update vsftpd openssl openssh
COPY src/vsftpd.conf /etc/vsftpd/vsftpd.conf
COPY src/run.sh /

RUN chmod +x ./run.sh
ENTRYPOINT [ "/run.sh" ]

