FROM  alpine:3.12.0

RUN apk update
RUN apk add openrc vim openssl
RUN apk add php7-common php7-iconv php7-json php7-gd php7-curl php7-xml \
	php7-mysqli php7-imap php7-cgi fcgi php7-pdo php7-pdo_mysql php7-soap php7-xmlrpc \
	php7-posix php7-mcrypt php7-gettext php7-ldap php7-ctype php7-dom php7 php7-fpm php7-opcache
RUN mkdir -p /var/www/html/
RUN wget "https://github.com/vrana/adminer/releases/download/v4.8.1/adminer-4.8.1.php"
# RUN mv /var/www/html/adminer.php /var/www/html/index.php
RUN mv adminer-4.8.1.php index.php
#RUN chown -R nginx:nginx /var/lib/nginx
#RUN chown -R nginx:nginx /var/www/html
# RUN openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/ssl/private/adminer-selfsigned.key -out /etc/ssl/certs/adminer-selfsigned.crt -subj "/C=MA/ST=Khouribga/L=Khouribga/O=1337/CN=Inception"
# COPY src/run.sh /
# RUN chmod +x ./run.sh
# ENTRYPOINT [ "./run.sh" ]
CMD php -S 0.0.0.0:5000